### ISSUE TITLE
[QUESTION]Unwanted auto rounding occur when a decimal column add or  subtract 0 without scale (execute by PrepareStatement )

### ISSUE THREAD

**Issue by murisans** [microsoft/mssql-jdbc#2262]
## Question

# Unwanted auto rounding occur when a decimal column add or subtract 0 without scale (execute by PrepareStatement )

- language: java

- driver: sqljdbc4: 4.0
```xml
<!-- https://mvnrepository.com/artifact/com.microsoft.sqlserver/sqljdbc4 -->
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>sqljdbc4</artifactId>
    <version>4.0</version>
</dependency>
```

- database server info:
Microsoft SQL Server 2008 (RTM) - 10.0.1600.22 (Intel X86) 
	Jul  9 2008 14:43:34 
	Copyright (c) 1988-2008 Microsoft Corporation
	Enterprise Edition on Windows NT 5.2 <X86> (Build 3790: Service Pack 2) (VM)

test data:
-- create
```
CREATE TABLE BILL (
  id int,
  amount decimal(19,4) --amount of money
);

-- insert
INSERT INTO BILL(id,amount) VALUES (1, 100.99);
INSERT INTO BILL(id,amount) VALUES (2, 100.99);

-- fetch 
SELECT * FROM BILL;

update bill set amount = amount + 0.00 where id  = 100

SELECT * FROM BILL;

GO
```
Output:

```
(1 rows affected)

(1 rows affected)
id          amount               
----------- ---------------------
          1              100.9900
          2              100.9900

(2 rows affected)

(0 rows affected)
id          amount               
----------- ---------------------
          1              100.9900
          2              100.9900

(2 rows affected)
```

reproduce case:
add 0 without scale to a decimal column will lead to auto rounding
```java
        String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url = "jdbc:sqlserver://ip:1433;databaseName=db1";
        String userName = "user";
        String pwd = "password";
        try{
            Class.forName(driver);
        }catch (ClassNotFoundException e){
            e.printStackTrace();
        }
        Connection con = null;
        try{
            con = DriverManager.getConnection(url,userName,pwd);
           // 0 and 0.00 should be the same number,but the results are different when added to a decimal column
           PreparedStatement ps = con.prepareStatement("update bill set amount = amount + ?  where id = ?");
           ps.setBigDecimal(1,BigDecimal.ZERO); // zero without scale
           ps.setBigDecimal(2,1);
           ps.execute();

           ps.setBigDecimal(1,new BigDecimal("0.00")); // zero with scale 2
           ps.setBigDecimal(2,2);
           ps.execute();

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }

```
```
Output:
the first record is auto rounded, and the second record is not affected

id          amount               
----------- ---------------------
          1              101.0000
          2              100.9900

(2 rows affected)
```

## Relevant Issues and Pull Requests

#1021 

fixed by #2248 
update the driver to  version higher than 12.5.0 preview release, then add a property `calcBigDecimalScale = true` in the db connection url, then the problem flies away!
```
String url = "jdbc:sqlserver://{host}:{port};databaseName={dbName};calcBigDecimalScale=true;"
```

**Comment by murisans** [comment]
actually if the number is a no scale decimal (0/0.00,1,1.00 should be the same) ,when it is added or subtracted to the decimal column, the value will be auto rounded

**Comment by Jeffery-Wasty** [comment]
Hi @murisans,

What is the driver version? Above you have the driver listed as `sqljdbc4-4.0` but that is not a valid version for this driver. However, this does look like a familiar issue that has recently been fixed with the latest preview release. If possible, we recommend using the 12.5.0 preview release, and turning on the connection string option `calcBigDecimalScale`. Please keep in mind, this option can cause slight performance issues, which is why it is off by default.

**Comment by murisans** [comment]
> Hi @murisans,
> 
> What is the driver version? Above you have the driver listed as `sqljdbc4-4.0` but that is not a valid version for this driver. However, this does look like a familiar issue that has recently been fixed with the latest preview release. If possible, we recommend using the 12.5.0 preview release, and turning on the connection string option `calcBigDecimalScale`. Please keep in mind, this option can cause slight performance issues, which is why it is off by default.
the driver version is  sqljdbc4 : 4.0

<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>sqljdbc4</artifactId>
    <version>4.0</version>
</dependency>

**Comment by murisans** [comment]
> Hi @murisans,
> 
> What is the driver version? Above you have the driver listed as `sqljdbc4-4.0` but that is not a valid version for this driver. However, this does look like a familiar issue that has recently been fixed with the latest preview release. If possible, we recommend using the 12.5.0 preview release, and turning on the connection string option `calcBigDecimalScale`. Please keep in mind, this option can cause slight performance issues, which is why it is off by default.
@Jeffery-Wasty 
I create a demo project and  use mssql-jdbc:6.4.0.jre8 ,the problem seems to be fixed;
however, the production environment use jdk6 only , is it possible to fix bugs for  sqljdbc4:4.0 and release a patch ?
``` xml
<!-- https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc -->
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>6.1.0.jre8</version>
</dependency>

```

**Comment by Jeffery-Wasty** [comment]
Unfortunately, we don't support 4.4.0 or 6.1.0 anymore. The oldest version we still support is version 7.2.0. My best recommendation is you take a look at other JDBC drivers and see if there is one that meets you needs.

**Comment by murisans** [comment]
> Unfortunately, we don't support 4.4.0 or 6.1.0 anymore. The oldest version we still support is version 7.2.0. My best recommendation is you take a look at other JDBC drivers and see if there is one that meets your needs.

got it! 
btw, I upgrade the driver to mssql-jdbc:9.4.1(cuz version higher than 9.4.1 has some problems in authentication) , the problem still exists, I am confused whether it is a driver bug or a database bug.

**Comment by murisans** [comment]
> Unfortunately, we don't support 4.4.0 or 6.1.0 anymore. The oldest version we still support is version 7.2.0. My best recommendation is you take a look at other JDBC drivers and see if there is one that meets your needs.

We believe in official drivers and look forward to other possible solutions :).

**Comment by murisans** [comment]
> Hi @murisans,
> 
> What is the driver version? Above you have the driver listed as `sqljdbc4-4.0` but that is not a valid version for this driver. However, this does look like a familiar issue that has recently been fixed with the latest preview release. If possible, we recommend using the 12.5.0 preview release, and turning on the connection string option `calcBigDecimalScale`. Please keep in mind, this option can cause slight performance issues, which is why it is off by default.

I tried 12.5.0 and use the option calcBigDecimalScale just now , the problem was fixed , I hope this feedback is useful to you!

**Comment by Jeffery-Wasty** [comment]
Yes, the issue was fixed in #2248, which is only available in the 12.5.0 preview release (for now). There are no current plans to backport this fix to 9.4. 

Please let us know if there is anything else we can help you with, otherwise we will go ahead and close this issue.

**Comment by murisans** [comment]
> Yes, the issue was fixed in #2248, which is only available in the 12.5.0 preview release (for now). There are no current plans to backport this fix to 9.4.
> 
> Please let us know if there is anything else we can help you with, otherwise we will go ahead and close this issue.

Nothing else, we will figure out another way to work around the problem.

**Comment by murisans** [comment]
> Please
Eventually our leader is convinced to update the driver , thanks a lot @Jeffery-Wasty ! Btw, Would you mind providing the same  string option calcBigDecimalScale in the database url and make it effective globally ? cuz it will be more convinient for us to ajust the project.

**Comment by Jeffery-Wasty** [comment]
I can't speak to JTDS, but for JDBC the behavior has caused issues for many users over the years, and so we have 'fixed' it in the form of an optional connection string option. The default behavior is to still process big decimal as decimal(38,0) though.

I'm not sure what you mean by "providing the same string option `calcBigDecimalScale` in the database url and make it effective globally". Properties are on a per-connection basis, and can already be set in the connection URL as seen [here](https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15) (this page will not include `calcBigDecimalScale` until the next stable release 12.6.0 is released). Can you provide a bit more explanation as to what you're looking for?

**Comment by murisans** [comment]
> I can't speak to JTDS, but for JDBC the behavior has caused issues for many users over the years, and so we have 'fixed' it in the form of an optional connection string option. The default behavior is to still process big decimal as decimal(38,0) though.
> 
> I'm not sure what you mean by "providing the same string option `calcBigDecimalScale` in the database URL and make it effective globally". Properties are on a per-connection basis, and can already be set in the connection URL as seen [here](https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15) (this page will not include `calcBigDecimalScale` until the next stable release, 12.6.0, is released). Can you provide a bit more explanation as to what you're looking for?

As you mentioned previously the option  `calcBigDecimalScale`  can already be set in the connection URL , That's exactly what I am looking for. Thanks a lot!

**Comment by Jeffery-Wasty** [comment]
Glad to hear that, closing issue.

**Comment by ecki** [comment]
What does it actually calculate? The scale of the parameter is 0, why would that help? Does it reduce its precision? Having said that should 0 always be DECIMAL(1)? (Does anybody happen to have the new links for the references linked above, I guess it’s about type conversions and arithmetic in Sql server?

**Comment by Jeffery-Wasty** [comment]
You may have a point, naming of the property changed around a bit during development, but reading scale was never an issue for the driver. There may have been a mix-up between precision and scale. We'll take a look if we want to change the property name, and update current documentation, ahead of our 12.6 release.

**Comment by ecki** [comment]
Another thing, i find it confusing that with literal expressions there is no mandated precision/scale, this might hurt a lot of developers who use prepared statements. I wonder, could the driver not set a scale at all for such (i.e. use only DECIMAL - that also reduces type variance)

Whats the actual performance problem here is it only the additional "client java guessing code" or does this also affect db performance, or is this also about the additional type variance in the statement handle cache?

**Comment by Jeffery-Wasty** [comment]
Mandating a precision or scale, or removing the ability to define scale, defeats the purpose of using BigDecimal. Furthermore, scale has never presented an issue when parsing BigDecimal. Scale is able to be parsed when the connection string option is both enabled and disabled. The only complaints we have received regarding the driver's parsing of BigDecimal was the use of maximum precision, and this has now been resolved.

Regarding the performance impact, this is seen in both #2171 and #2163. We've tested the driver with the option enabled and do notice a performance impact when using the option to parse BigDecimal.

Regarding the naming, thank you for your suggestion @ecki. We have introduced a PR to change the name of the option (#2269) ahead of our 12.6 GA release.

**Comment by murisans** [comment]
> Mandating a precision or scale, or removing the ability to define scale, defeats the purpose of using BigDecimal. Furthermore, scale has never presented an issue when parsing BigDecimal. Scale is able to be parsed when the connection string option is both enabled and disabled. The only complaints we have received regarding the driver's parsing of BigDecimal was the use of maximum precision, and this has now been resolved.
> 
> Regarding the performance impact, this is seen in both #2171 and #2163. We've tested the driver with the option enabled and do notice a performance impact when using the option to parse BigDecimal.
> 
> Regarding the naming, thank you for your suggestion @ecki. We have introduced a PR to change the name of the option (#2269) ahead of our 12.6 GA release.

#2112
